name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v3
    - name: Steup Node
      uses: action/setup-node@v3
    - run: npm ci
    - run: npm test
